package com.michael1142.springmvc.respositoy;

import com.michael1142.springmvc.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface ProductRepository extends JpaRepository<Product, Long> {
    // very cool! This 'custom' query is generated by the name we give the method
    Optional<List<Product>> findProductByName(String name);
    // this is a modification that will do a like % search
    Optional<List<Product>> findProductByNameContainingIgnoreCase(String name);
}
